export const currencyFlagMap = {
  USD: '🇺🇸',
  EUR: '🇪🇺',
  GBP: '🇬🇧',
  JPY: '🇯🇵',
  CNY: '🇨🇳',
  VND: '🇻🇳',
  KRW: '🇰🇷',
  AUD: '🇦🇺',
  CAD: '🇨🇦',
  CHF: '🇨🇭',
  SGD: '🇸🇬',
  THB: '🇹🇭',
  MYR: '🇲🇾',
  IDR: '🇮🇩',
  INR: '🇮🇳',
  PHP: '🇵🇭',
  HKD: '🇭🇰',
  TWD: '🇹🇼',
  NZD: '🇳🇿',
  SEK: '🇸🇪',
  NOK: '🇳🇴',
  DKK: '🇩🇰',
  PLN: '🇵🇱',
  CZK: '🇨🇿',
  HUF: '🇭🇺',
  RON: '🇷🇴',
  TRY: '🇹🇷',
  ZAR: '🇿🇦',
  BRL: '🇧🇷',
  MXN: '🇲🇽',
};

export const flagForCurrency = (code) => currencyFlagMap[code?.toUpperCase?.()] || '';
